# Generated by Django 4.0.10 on 2023-09-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipApp', '0002_alter_message_email_alter_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='value',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
