# Generated by Django 4.0.10 on 2023-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadershipApp', '0003_studentrecord_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='student_full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
